trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'ShutterPage/src'

parameters:

- name: envToDeploy
  displayName: Target env to deploy
  default: development
  type: string
  values:
    - development
    - test
    - preprod
    - prod

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/${{ parameters.envToDeploy }}.yaml
  

resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: main

jobs:
  - job: copying_ShutterPage
    displayName: Copying Shutter page to ${{ parameters.envToDeploy }}
    steps:
      - template: templates/shutter-page.yaml@CommonTemplates
        parameters:
          azureSubscription: $(azureSubscription)
          storage: $(storage)
  
  - job: reset_Application_Gateway
    # condition: or(eq(parameters.envToDeploy,'development'), eq(parameters.envToDeploy,'test'), eq(parameters.envToDeploy,'preprod'), eq(parameters.envToDeploy,'prod'))
    dependsOn: copying_ShutterPage
    steps:
      - task: AzurePowerShell@5
        displayName: Reset Application Gateway
        inputs:
          azureSubscription: '$(application_gateway_service_Connection)'
          scriptType: filePath
          scriptPath: pipelines/powershell/resetApplicationGatewayCustomeError.ps1
          scriptArguments: -gatewayName $(application_gateway_name) -applicationGatewayRg $(application_gateway_rg)
          azurePowerShellVersion: latestVersion
          pwsh: true
