trigger:
  branches:
    include:
      - '*'
  paths:
    include:
      - 'ShutterPage/src'

parameters:

- name: envToDeploy
  displayName: Target env to deploy
  default: development
  type: string
  values:
    - development
    - test
    - preprod
    - prod

pool: DEFRA-COMMON-ubuntu2004-SSV3

variables:
  - template: vars/${{ parameters.envToDeploy }}.yaml
  - name: application_gateway_service_Connection
    value: 365-CSC-SEC1_RWD-DEV
  - name: application_gateway_rg
    value: SECINFNETRG1401



resources:
  repositories:
    - repository: CommonTemplates
      name: RWD-CPR-EPR4P-ADO/epr-webapps-code-deploy-templates
      type: git
      ref: main

jobs:
  - job: copying_ShutterPage
    displayName: Copying Shutter page to ${{ parameters.envToDeploy }}
    steps:
      - template: templates/shutter-page.yaml@CommonTemplates
        parameters:
          azureSubscription: $(azureSubscription)
          storage: $(storage)
  
  - job: reset_Application_Gateway
    steps:
      - task: AzurePowerShell@5        
        displayName: reset Application Gateway
        inputs:
          azureSubscription: '$(application_gateway_service_Connection)'
          targetType: filePath
          filePath:  pipelines/powershell/resetApplicationGatewayCustomeError.ps1
          arguments: -gatewayServiceConnection $(application_gateway_service_Connection) -applicationGatewayRg $(application_gateway_rg) 