variables:
- group: ServiceConnections
- name: azureSubscription
  value: $(ServiceConnectionPRD1)
- name: storage
  value: 'prdrwddbssa1402'
- name: application_gateway_service_Connection
  value: 'AZR-CSC-SEC1_RWD-PRD'
- name: application_gateway_rg
  value: 'SECRWDPRDRG1401'
- name: application_gateway_name
  value: 'SECRWDPRDAG1401'